# Generated by Django 5.0.2 on 2024-02-17 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, verbose_name='Nombres')),
                ('Apell', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('Tit', models.CharField(max_length=100, verbose_name='Titulo')),
                ('perfil', models.CharField(max_length=100, verbose_name='Perfil')),
                ('tel', models.CharField(max_length=100, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('Descrip', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
            ],
            options={
                'verbose_name': 'Acerca de mi',
                'verbose_name_plural': 'Acerca de mi',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msj', models.TextField(verbose_name='Mensaje')),
                ('drc', models.CharField(max_length=200, verbose_name='Direccion')),
                ('fcb', models.URLField(max_length=300, verbose_name='Enlace a Facebook')),
                ('itg', models.URLField(max_length=300, verbose_name='Enlace a Instagram')),
                ('wsp', models.URLField(max_length=300, verbose_name='Enlace a Whatsapp')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('about', models.ManyToManyField(to='core.about')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Espe', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('about', models.ManyToManyField(to='core.about')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leng', models.CharField(max_length=100, verbose_name='Lenguajes')),
                ('porc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El valor no puede ser menor que 0.'), django.core.validators.MaxValueValidator(100, message='El valor no puede ser mayor que 100.')], verbose_name='Porcentaje')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('about', models.ManyToManyField(to='core.about')),
            ],
            options={
                'verbose_name': 'Lenguaje',
                'verbose_name_plural': 'Lenguajes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de proyecto')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('fecha', models.DateField(verbose_name='Fecha de creacion')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('detall', models.TextField(verbose_name='Detalle')),
                ('img1', models.ImageField(upload_to='img/', verbose_name='Imagen 1')),
                ('img2', models.ImageField(upload_to='img/', verbose_name='Imagen 2')),
                ('img3', models.ImageField(upload_to='img/', verbose_name='Imagen 3')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('about', models.ManyToManyField(to='core.about')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svc', models.CharField(max_length=150, verbose_name='Nombre del servicio')),
                ('dcpc', models.TextField(verbose_name='Descripcion')),
                ('icon', models.CharField(max_length=50, verbose_name='Icono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('about', models.ManyToManyField(to='core.about')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created'],
            },
        ),
    ]
