# Generated by Django 5.0.2 on 2024-02-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lenguaje_about_remove_lenguaje_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Apell',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Descrip',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='about',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='about',
        ),
        migrations.AddField(
            model_name='about',
            name='imga1',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Imagen1'),
        ),
        migrations.AddField(
            model_name='about',
            name='imga2',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Imagen2'),
        ),
        migrations.AddField(
            model_name='about',
            name='imga3',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Imagen2'),
        ),
    ]
