# Generated by Django 5.0.2 on 2024-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_about_apell_remove_about_descrip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='nom',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre Vehiculo'),
            preserve_default=False,
        ),
    ]
