# Generated by Django 5.0.2 on 2024-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_about_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portafolio',
            options={'ordering': ['-created'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='portafolio',
            name='icon',
            field=models.CharField(default=1, max_length=100, verbose_name='Icono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='detall',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Titulo Servicios'),
        ),
    ]
